### ISSUE TITLE
Followed instructions, didn't work.

### ISSUE THREAD

**Issue by inmento** [Snackya/KH2PC-rando-setup-guide#1]
Okay so I followed all the steps for the internal version, and I booted a new game (figured loading my save wouldn't work) and instead of starting in the Garden, the game started as normal. One caveat I will add is that I have the current version cracked to run without needing to open the launcher (pc likes to randomly use up all my ram so the less I have running in the background, like game launchers, the better) if the crack is the issue, I can always try taking it off and seeing if that worked.

Update: removing the crack and uninstalling (fully) and reinstalling the game and then the rando, same result, no proper loading into the garden, game starts as normal. I followed the steps to a t.

**Comment by Snackya** [comment]
Hi, please ask for help in the official KH2FM Rando Discord, if you don't mind, as direct messaging resolves problems a lot faster than a github issue.
Here is the invite link: https://discord.gg/KwfqM6GYzd
