### ISSUE TITLE
Entry exception

### ISSUE THREAD

**Issue by TearzZzSSB** [Snackya/KH2PC-rando-setup-guide#2]
I've followed the Instalation steps and when i execute the game it sais "Entry exception: File could not be opening for reading Scripts failed to load", and i don't know what to do, if someone know whould be helpful, Thanks ^^

**Comment by Snackya** [comment]
This guide has been deprecated for a while because of a lot of changes to the KH2 rando environment. Please use this guide instead: https://tommadness.github.io/KH2Randomizer/setup/Panacea-ModLoader/
